console docker file deployment fixes

diff --git a/interfaces/console/Dockerfile b/interfaces/console/Dockerfile
--- a/interfaces/console/Dockerfile
+++ b/interfaces/console/Dockerfile
@@ -1,17 +1,44 @@
-FROM node:18-alpine AS runner
+FROM node:20-alpine AS base
+
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
+
+COPY package.json yarn.lock* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+RUN yarn build
+
+FROM base AS runner
+WORKDIR /app
+
 ENV NODE_ENV production
+
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
-COPY ./public ./public
-COPY ./package.json ./package.json
-COPY --chown=nextjs:nodejs ./.next ./
-COPY --chown=nextjs:nodejs ./.next/static ./.next/static
+
+COPY --from=builder /app/public ./public
+
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 
 EXPOSE 8080
 
 ENV PORT 8080
+ENV HOSTNAME "0.0.0.0"
 
 CMD ["node", "server.js"]
