Added support for cleaning and building coreboot/musl toolchains.

diff --git a/firmware/Makefile b/firmware/Makefile
--- a/firmware/Makefile
+++ b/firmware/Makefile
@@ -6,8 +6,9 @@ CURMAKE := $(abspath $(firstword $(MAKEFILE_LIST)))
 CURDIR := $(dir $(CURMAKE))
 
 #Targets based on boards
+COREBOOTSRC = coreboot
 ANODETARGET = at91bootstrap uboot
-CNODETARGET = coreboot 
+CNODETARGET = $(COREBOOTSRC) 
 AT91BOOTSTRAPBIN = at91bootstrap.bin
 UBOOTBIN = u-boot.bin
 COREBOOTBIN = coreboot.rom
@@ -16,12 +17,15 @@ COREBOOTBIN = coreboot.rom
 ifndef ROOTFSPATH
 override ROOTFSPATH = $(CURPATH)_ukamafs
 endif
-ROOTFSKPATH=$(ROOTFSPATH)/boot
+ROOTFSKPATH = $(ROOTFSPATH)/boot
 
 # Config for Builds
-AT91CONFIG = ukama_anode_eMMC_uboot_defconfig
-UBOOTCONFIG = sama5d27_ukama_anode_emmc_defconfig
-CBCONFIG = config.ukama_comv1_16mb
+AT91CONFIG := ukama_anode_eMMC_uboot_defconfig
+UBOOTCONFIG := sama5d27_ukama_anode_emmc_defconfig
+CBCONFIG := config.ukama_comv1_16mb
+# Path to coreboot tool chain
+COREBOOTXCCPATH := $(COREBOOTSRC)/util/crossgcc/xgcc
+COREBOOTXCC := i386-elf-gcc
 
 #Set build parameters based on targets
 ifeq ($(ANODEBOARD), $(TARGETBOARD))
@@ -33,6 +37,18 @@ ifeq ($(CNODEBOARD), $(TARGETBOARD))
 override ARCH = $(ARCHX86)
 SRCDIRS = $(CNODETARGET)
 endif
+
+define checkxcc
+	@echo Checking for coreboot toolchain.
+	$(shell if [ ! -f "$(COREBOOTXCCPATH)/bin/$(COREBOOTXCC)" ] ; then \
+		(echo "$(MAKE) -C $(COREBOOTSRC) crossgcc-i386 CPUS=$(NPROCS)") \
+	fi;)
+
+endef
+
+#make crossgcc-i386 CPUS=$(NPROCS)
+#$(shell test -s $(COREBOOTXCC) || { echo "Coreboot toolcahin missing.Staring build for one"; \
+#	cd $(COREBOOTXCC) && $(MAKE) crossgcc-i386 CPUS=$(NPROCS); })
 
 
 .PHONY: subdirs $(SRCDIRS) info
@@ -61,8 +77,9 @@ uboot:
 coreboot:
 	@echo Building $@
 	mkdir -p $(ROOTFSKPATH)/$@
+	$(call checkxcc)
 	(cd $@ && cp -v configs/config.ukama_comv1_16mb .config)
-	$(MAKE) -j$(NPROCS) -C $@ ARCH=$(ARCH) CROSS_COMPILE=$(CC)
+	$(MAKE) -j$(NPROCS) -C $@ 
 	@echo Copy $@/build/$(COREBOOTBIN) $(ROOTFSKPATH)/$@/$(COREBOOTBIN)
 	(cp -v $@/build/$(COREBOOTBIN) $(ROOTFSKPATH)/$@/$(COREBOOTBIN))
 
@@ -79,6 +96,15 @@ clean :
 	for dir in $(SRCDIRS); do \
 		$(MAKE) -j$(NPROCS) -C $$dir -f Makefile $@; \
         done
+
+distclean:
+	@echo DistClean started for firmware.
+	for dir in $(SRCDIRS); do \
+                $(MAKE) -C $$dir -f Makefile $@; \
+        done
+	rm -rf $(COREBOOTXCCPATH) 
+	rm -rf $(ROOTFSPATH)
+	rm -rf *.img
 
 info: ; 
 	$(info [$@] Building $(TARGETBOARD) for $(ARCH) with $(CC) )
